server:
  port: 9999  
spring:  
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/salesdemo?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/salesdemo?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=root
#logging.level.root=WARN

# logging:
#   level:
#     root: WARN
